version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.4
    working_directory: ~/app

    steps:
      - checkout
      - run:  git config --global user.email "1141591465@qq.com"
      - run:  git config --global user.name "dalongrong"
      - run:  cd ~/app/website && yarn install
      - run:  cd ~/app/website && yarn build
      - run:  cd ~/app/website && GIT_USER=rongfengliang USE_SSH=true yarn run publish-gh-pages